# Generated by Django 4.2.1 on 2023-06-01 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_alter_product_users_wishlist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='author',
            field=models.CharField(max_length=21),
        ),
        migrations.AlterField(
            model_name='product',
            name='limba',
            field=models.CharField(max_length=21),
        ),
        migrations.AlterField(
            model_name='product',
            name='title',
            field=models.CharField(max_length=42),
        ),
    ]
