# Generated by Django 4.2.1 on 2023-06-01 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_alter_product_author_alter_product_limba_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='author',
            field=models.CharField(max_length=19),
        ),
        migrations.AlterField(
            model_name='product',
            name='limba',
            field=models.CharField(max_length=19),
        ),
    ]
